scripts/example.coffee
=> KEEEEEEEEE

scripts/saluda.coffee
lo siento puducito no me retes
=> estúpido error de variable!

scripts/julio.coffee
=> un vampirito

scripts/julio.coffee
=> mejoras a julio

scripts/translate.coffee
pudu traduce `termino`
pudu traduce de `idioma1` a ìdioma2` `termino idioma1`
=> translate now works

scripts/uselessweb.coffee
@pudo uselessweb - devuelve una url a un sitio para quedar pegado un rato
=> Para perder el tiempo un rato

scripts/azar.js
=> al azar de un conj. separados por coma

external-scripts.json, package.json
=> hubot-numbersapi

scripts/dameunatarjeta.coffee
Ahora funciona, los descarados cambiaron la página y no me avisaron.
=> Fix dame una tarjeta

scripts/futbolero.coffee, scripts/recordador.coffee
a pedido de @eseceve en #ideas
=> @pudu frase futbolera

scripts/guruguru.coffee
=> @pudu guru <texto a gurugizar>

package.json, scripts/pinera.coffee
reconocía hasta ‘opinion’ estaba loco ahora solo
`piñera|PIÑERA|yeta|YETA`
=> REGEX fixed

scripts/votador.coffee
=> Pudu votador

scripts/avisar.js
Agregué un script para avisar en multiples canales y por DM.
Falta probar que `robot.send({room: []}, message)` funcione bien. No lo pude testear en la consola.
=> WIP - avisar

scripts/avisar.js
=> feat(avisar): agregar comando

scripts/finvox.coffee
demasiado lento, chao, muérete, vales callampa miindicador.cl
=> cambio API para datos de indicadores

scripts/finvox.coffee
mejoras con API de getonbrd y bitcoin
=> mejoras con API de getonbrd y bitcoin

scripts/yelp.coffee
primera version. me dio hambre.
=> Nuevo: Yelp

scripts/yapo.coffee
si latea mucho lo desactivamos porq esta con ‘hear’
=> nuevo poh en honor a @eseceve

scripts/imdb.coffee
=> Added more options 👌, poster was removed 💀

scripts/finvox.coffee, scripts/temblor.js
lo hice en JS para q no aleguen los alerones de siempre… :eyes:
=> nuevo después tel terremoto y replica de este '18' 2015

package.json, scripts/dameunaclave.coffee
* Se agrega librería `password-generator`
* Se agrega opción de elegir el largo de la clave, ej: `dame una clave 30`, entrega una clave de 30 caracteres.
* Se quita `cheerio`
=> Hiper mejoras de velocidad

scripts/saluda.coffee
pude menciona a quien entra a #general
=> este si q si el otro no

scripts/tusecreto.coffee
a produccion la wea ql la shit de la shit
=> Ahora el secreto se muestra en #random

scripts/tusecreto.coffee
newbie error, plz don't tell anyone.
=> removed fucking whitespace

scripts/fue-rematado.coffee
Mientras dure la url que levantaron en t13.cl
=> Para saber si un auto ha sido rematado

external-scripts.json, package.json
Revisa el email usando la api de https://hesidohackeado.com
=> Se agrego script `pudu hesidohackeado <email>`

scripts/feed.coffee
Feeds pudu when it deserves it or when he's starving.
=> Feed pudu 😋

scripts/saluda.coffee
> commitead y mergead todos de él.
- Jebús
=> Nuevo msg de saludo introductorio de :pudu: ql

scripts/agencias.coffee
=> muestra un gif relacionado con la asombrosa experiencia de trabajar en agencia

scripts/beerjs.js
:skull: nunca valido ahora lo hice :skull:
=> validando si info esta vacia

scripts/nasa.js
=> nuevo: muestra foto del día desde api.nasa.gov

scripts/timezone.coffee
feo el fix lo hizo otro no :jorge:
=> fixeado si minuto menor a 10 sin cero se lo agregue a manopla nomas

scripts/finvox.coffee
se cambio la forma de describir el valor del ₲
=> sugerencia de :gmq:

README.md
por si preguntan de nuevo mando a RTFM
=> agregado pasos

scripts/conversador.js
el prox. intento es con natural language
=> primer intento de un :pudu: que interactua

scripts/karma.coffee
https://www.npmjs.com/package/hubot-karma
=> added karma script

scripts/citas.coffee
andas cansado, desanimado, desestimado? que :pudu: te entregue una
inspiradora cita al azar.
=> nuevo script inspirador

scripts/errorcodes.coffee
Retorna un error-code-cat si un error es mencionado
=> nuevo :cat2:

scripts/torrent.js
- usa torrentproject.se y extrae los primero 6 resultados
- mejora en mensaje previo al envío del string de búsqueda
=> nuevo: busca el torrent dado un string

scripts/torrent.js
este es un test de envío de enlace con hubot aver como lo muestra
:pudu: ql
=> test link a hubot

scripts/last-fm.js
Se mejoro la exp regular para validar el respond, se formatean los request de last con url.format de node y se simplifico la logica
=> Refactoring

scripts/math.js
:hector: instala mathjs como dependencia plz
=> nuevo: :pudu: mateo hace el calculo por ti
